### ISSUE TITLE
Data package 'string' TypeError

### ISSUE THREAD

**Issue by brynpickering** [sentinel-energy/sentinel-archive#1]
When attempting to create a dataframe, I get a TypeError due to a string data column. Error occurs on different data packages, if a 'string' data column is present.

Example data: https://data.sccer-jasm.ch/building-archetype-space-heating-demand/opsd-building-archetype-space-heating-demand-2019-02-08.zip

MWE:

```python
from sark import dpkg

pkg = dpkg.read_pkg('opsd-building-archetype-space-heating-demand-2019-02-08/datapackage.json')
dfs = [dpkg.to_df(res) for res in pkg.resources]  # Raises TypeError
```

**Comment by suvayu** [comment]
Sorry, the requirements file doesn't list version numbers.  You need `pandas` 1.0.  Thanks to this, I realised I'm also using a `glom.Iter()`, which is available only in the latest release of `glom`.
